blank_issues_enabled: false
contact_links:
  - name: 🤖 AI Development Guide
    url: https://github.com/developer-az/hypotrophy/blob/main/AI_DEVELOPMENT_GUIDE.md
    about: Comprehensive guide for AI-enhanced development workflows
  - name: 💬 GitHub Discussions
    url: https://github.com/developer-az/hypotrophy/discussions
    about: Community discussions, questions, and best practices sharing
  - name: 📚 Copilot Documentation
    url: https://docs.github.com/en/copilot
    about: Official GitHub Copilot documentation and guides